package com.ytripapp.domain;

public enum Authority {

    ROLE_GUEST,
    ROLE_HOST,
    ROLE_EDITOR,
    ROLE_ADMIN,
    ROLE_GATEWAY,

    ROLE_ADMIN_LISTING_AUDIT,
    ROLE_ADMIN_EVENT_AUDIT,
    ROLE_ADMIN_BOOING_AUDIT,
    ROLE_ADMIN_ARTICLE_AUDIT

}
